export const industry = [
  "Agriculture",
  "Automotive",
  "Computers & Electronics",
  "Consumer Goods",
  "Education",
  "Financial Services",
  "Gaming",
  "Government",
  "Healthcare",
  "Hospitality",
  "Life Sciences",
  "Manufacturing",
  "Marketing and Advertising",
  "Media & Entertainment",
  "Mining",
  "Non-Profit Organization",
  "Oil & Gas",
  "Other",
  "Power & Utilities",
  "Professional Services",
  "Real Estate & Construction",
  "Retail",
  "Software & Internet",
  "Telecommunications",
  "Travel",
  "Transportation & Logistics",
  "Wholesale & Distribution",
];

export const companyType = [
  "Enterprise",
  "Government / Public Sector",
  "Government – Federal",
  "Government – State & Local",
  "Non-Profit",
  "Self Employed",
  "Small-Medium Business",
  "Start-Up",
  "Not Applicable",
];

export const companySize = [
  "1-19 Employees",
  "20-99 Employees",
  "100-499 Employees",
  "500-999 Employees",
  "1000-9999 Employees",
  "10000+ Employees",
];
