export default {
  breakpoints: ["350px", "992px", "1200px", "1650px"],
  colors: {
    white: "#FFFFFF",
    // buttonText: "#0518C2",
    // blue: "#00065D",
    // lightBlue: "#00BFBF",
    black: "#2F2F2F",
    lightWhite: "#F8F8FE",
    lightGreen: "#00FEB7",
    purple: "#8F97EE",
    black2: "#1C1C1C",
    lightGreen2: "#E5F8F8",
    darkGreen: "#00516E",
    darkCyan: "#003A42",
    primaryBlue: "#0518C2",
    secondaryBlue: "#00065D",
    bgLightBlue: "#D6DBFD",
    specialColor: "#DB7800",
    bgSpecialColor: "#FFF3D2",
    specialGreen: "#00DAB2",
    bgSpecialGreen: "#00BBAA",
    lightBlue: "#C4CAFA",
    secondaryWhite: "#F7F7F7",
  },
  fonts: {
    avenir: "Avenir",
  },
  fontSizes: [10, 15, 16, 32, 48, 60, 96],
  lineHeights: {
    heading: "131px",
    subHeading: "82px",
    subHeading2: "65px",
    text: "21px",
    smallText: "28px",
    paragraph: "48px",
  },
  fontWeights: {
    normal: 400,
    medium: 500,
    bold: 700,
    extraBold: 900,
  },
  text: {
    heading: {
      fontSize: ["48px", "48px", 6],
      fontFamily: "avenir",
      lineHeight: ["66px", "66px", "heading"],
      fontWeight: "bold",
      letterSpacing: "1px",
      // width: "max-content",
    },
    mobileHeading: {
      fontSize: "24px",
      fontFamily: "avenir",
      lineHeight: "32px",
      fontWeight: "medium",
      letterSpacing: "1px",
    },
    subHeading: {
      fontSize: ["24px", "24px", 5],
      fontFamily: "avenir",
      lineHeight: ["32px", "32px", "subHeading"],
      fontWeight: "medium",
      letterSpacing: ["1px", "1px", "3.33px"],
      // width: "max-content",
    },
    mobileSubHeading: {
      fontSize: "15px",
      fontFamily: "avenir",
      lineHeight: "20px",
      fontWeight: "medium",
      letterSpacing: "1.11px",
    },
    buttonText: {
      fontSize: [2],
      fontFamily: "avenir",
      lineHeight: "22px",
      fontWeight: "medium",
      color: "primaryBlue",
    },
    headerText: {
      fontSize: [2],
      lineHeight: "22px",
      fontFamily: "avenir",
      lineHeight: "text",
      fontWeight: "medium",
      color: "white",
    },
    subHeading2: {
      fontSize: [5],
      // fontFamily: "avenir heavy",
      lineHeight: "subHeading",
      fontWeight: "extraBold",
      width: "max-content",
      color: "secondaryBlue",
    },
    mobileSubHeading2: {
      fontSize: "24px",
      fontFamily: "avenir",
      lineHeight: "32px",
      fontWeight: "extraBold",
      // width: "max-content",
      color: "secondaryBlue",
    },
    paragraph: {
      fontSize: [3],
      fontFamily: "avenir",
      lineHeight: "paragraph",
      fontWeight: "medium",
      color: "black",
    },
    mobileParagraph: {
      fontSize: "15px",
      fontFamily: "avenir",
      lineHeight: "24px",
      fontWeight: "medium",
      color: "black",
    },
    small: {
      fontSize: ["18px"],
      fontFamily: "avenir",
      lineHeight: "smallText",
      color: "black",
      fontWeight: "bold",
    },
    mobileSmall: {
      fontSize: "14px",
      fontFamily: "avenir",
      lineHeight: "20px",
      color: "black",
      fontWeight: "medium",
    },
  },
  button: {
    rounded: {
      borderRadius: "20px",
      border: "1px solid #00FEB7",
      bg: "#00FEB7",
      color: "primaryBlue",
      fontSize: [1],
      lineHeight: "20px",
      cursor: "pointer",
    },
    rounded2: {
      borderRadius: "24px",
      // width: 282,
      bg: "secondaryBlue",
      color: "white",
      fontSize: '16px',
      lineHeight: '21px',
      fontWeight: 900,
      cursor: "pointer",
    },
    outlined: {
      borderRadius: "20px",
      border: "1px solid #00FEB7",
      bg: "transparent",
      color: "white",
      fontSize: [1],
      lineHeight: "20px",
      cursor: "pointer",
    },
    lightGreenOutlined: {
      borderRadius: "20px",
      border: "1px solid #00FEB7",
      // borderColor: "lightGreen",
      bg: "transparent",
      color: "black",
      fontSize: [2],
      lineHeight: "22px",
      // fontFamily: 'Avenir Roman'
      cursor: "pointer",
    },
  },
  forms: {
    checkbox: {
      "input:checked ~ &": {
        color: "secondaryBlue",
      },
    },
    input: {
      "&::placeholder": {
        color: "black",
      },
    },
    textarea: {
      "&::placeholder": {
        color: "black",
      },
    },
  },
};
